import type { Property } from "@/components/property-card"

export const properties: Property[] = [
  {
    id: "1",
    title: "Modern Downtown Apartment",
    price: 450000,
    location: "Manhattan, New York",
    type: "apartment",
    listingType: "buy",
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    image: "/images/property-1.jpg",
    featured: true,
  },
  {
    id: "2",
    title: "Luxury Beachfront Villa",
    price: 1250000,
    location: "Miami Beach, Florida",
    type: "villa",
    listingType: "buy",
    bedrooms: 5,
    bathrooms: 4,
    area: 4500,
    image: "/images/property-2.jpg",
    featured: true,
  },
  {
    id: "3",
    title: "Cozy Studio in Arts District",
    price: 1800,
    location: "Los Angeles, California",
    type: "studio",
    listingType: "rent",
    bedrooms: 1,
    bathrooms: 1,
    area: 550,
    image: "/images/property-3.jpg",
  },
  {
    id: "4",
    title: "Family Home with Garden",
    price: 680000,
    location: "Austin, Texas",
    type: "house",
    listingType: "buy",
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    image: "/images/property-4.jpg",
  },
  {
    id: "5",
    title: "Penthouse with City Views",
    price: 5500,
    location: "Chicago, Illinois",
    type: "apartment",
    listingType: "rent",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    image: "/images/property-5.jpg",
    featured: true,
  },
  {
    id: "6",
    title: "Charming Victorian House",
    price: 890000,
    location: "San Francisco, California",
    type: "house",
    listingType: "buy",
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    image: "/images/property-6.jpg",
  },
  {
    id: "7",
    title: "Modern Loft Space",
    price: 2800,
    location: "Brooklyn, New York",
    type: "apartment",
    listingType: "rent",
    bedrooms: 1,
    bathrooms: 1,
    area: 900,
    image: "/images/property-7.jpg",
  },
  {
    id: "8",
    title: "Suburban Family Estate",
    price: 1100000,
    location: "Seattle, Washington",
    type: "house",
    listingType: "buy",
    bedrooms: 5,
    bathrooms: 4,
    area: 3500,
    image: "/images/property-8.jpg",
  },
]

export interface Agency {
  id: string
  name: string
  description: string
  location: string
  propertiesCount: number
  rating: number
  image: string
  specialties: string[]
}

export const agencies: Agency[] = [
  {
    id: "1",
    name: "Premier Properties Group",
    description: "Leading luxury real estate agency with over 20 years of experience in high-end residential and commercial properties.",
    location: "New York, NY",
    propertiesCount: 245,
    rating: 4.9,
    image: "/images/agency-1.jpg",
    specialties: ["Luxury Homes", "Penthouses", "Commercial"],
  },
  {
    id: "2",
    name: "Coastal Living Realty",
    description: "Specialists in beachfront and coastal properties, helping clients find their perfect waterfront home.",
    location: "Miami, FL",
    propertiesCount: 189,
    rating: 4.8,
    image: "/images/agency-2.jpg",
    specialties: ["Beachfront", "Vacation Homes", "Condos"],
  },
  {
    id: "3",
    name: "Urban Nest Real Estate",
    description: "Modern agency focused on urban living spaces, from trendy studios to spacious downtown apartments.",
    location: "Los Angeles, CA",
    propertiesCount: 312,
    rating: 4.7,
    image: "/images/agency-3.jpg",
    specialties: ["Apartments", "Lofts", "Urban Living"],
  },
  {
    id: "4",
    name: "Heritage Home Finders",
    description: "Dedicated to historic and character homes, we help preserve architectural heritage while finding you your dream home.",
    location: "San Francisco, CA",
    propertiesCount: 156,
    rating: 4.9,
    image: "/images/agency-4.jpg",
    specialties: ["Historic Homes", "Victorian", "Craftsman"],
  },
  {
    id: "5",
    name: "Family First Realty",
    description: "Helping families find the perfect home in the best neighborhoods with excellent schools and amenities.",
    location: "Austin, TX",
    propertiesCount: 278,
    rating: 4.8,
    image: "/images/agency-5.jpg",
    specialties: ["Family Homes", "Suburbs", "New Construction"],
  },
  {
    id: "6",
    name: "Metropolitan Realtors",
    description: "Full-service real estate firm serving the greater metropolitan area with personalized attention.",
    location: "Chicago, IL",
    propertiesCount: 421,
    rating: 4.6,
    image: "/images/agency-6.jpg",
    specialties: ["All Properties", "Investment", "Rentals"],
  },
]
